// Command gendocs regenerates docs/ENDPOINTS.md from internal/endpoints.yaml,
// the single source of truth for endpoint coverage. CI runs this and fails
// the build if the working tree then shows a diff, so docs/ENDPOINTS.md
// can never drift from what's actually implemented.
//
// Run: go run ./internal/gendocs
package main

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

type endpoint struct {
	Method      string `yaml:"method"`
	AccountMode string `yaml:"account_mode"`
	Domain      string `yaml:"domain"`
	HTTPMethod  string `yaml:"http_method"`
	Path        string `yaml:"path"`
	Access      string `yaml:"access"`
	Permission  string `yaml:"permission"`
	Status      string `yaml:"status"`
	Test        string `yaml:"test"`
	DocURL      string `yaml:"doc_url"`
}

type abandoned struct {
	Method string `yaml:"method"`
	Reason string `yaml:"reason"`
	DocURL string `yaml:"doc_url"`
}

type manifest struct {
	Endpoints []endpoint  `yaml:"endpoints"`
	Abandoned []abandoned `yaml:"abandoned"`
}

func main() {
	raw, err := os.ReadFile("internal/endpoints.yaml")
	if err != nil {
		fmt.Fprintln(os.Stderr, "gendocs: read internal/endpoints.yaml:", err)
		os.Exit(1)
	}

	var m manifest
	if err := yaml.Unmarshal(raw, &m); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs: parse internal/endpoints.yaml:", err)
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("# Endpoint Coverage Map\n\n")
	b.WriteString("Generated from [internal/endpoints.yaml](../internal/endpoints.yaml) by `go run ./internal/gendocs` — do not edit this file by hand, edit the manifest and regenerate.\n\n")
	b.WriteString("| Method | Account Mode | Domain | HTTP | Path | Access | Permission | Status | Test | Docs |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|---|---|\n")
	for _, e := range m.Endpoints {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | `%s` | %s | %s | %s | %s | [Link](%s) |\n",
			e.Method, e.AccountMode, e.Domain, e.HTTPMethod, e.Path, e.Access, e.Permission, e.Status, e.Test, e.DocURL)
	}

	b.WriteString("\n## Not Supported / Abandoned\n\n")
	if len(m.Abandoned) == 0 {
		b.WriteString("None tracked yet for this Phase-1 checkpoint. See KuCoin's [abandoned-endpoints introduction](https://www.kucoin.com/docs-new/abandoned-endpoints/introduction) for the platform-wide list.\n")
	} else {
		b.WriteString("| Method | Reason | Docs |\n|---|---|---|\n")
		for _, a := range m.Abandoned {
			fmt.Fprintf(&b, "| `%s` | %s | [Link](%s) |\n", a.Method, a.Reason, a.DocURL)
		}
	}

	b.WriteString("\n## Everything else (not yet implemented)\n\n")
	b.WriteString("This is a Phase-1 checkpoint covering UTA Market only. Every other domain in the brief — UTA Account/Orders/Positions/Leverage/Transfers, Classic Spot/Margin/Futures market data and trading, and all WebSocket channels — is not yet implemented. See the root [README.md](../README.md#status) for the honest current-vs-planned breakdown.\n")

	if err := os.WriteFile("docs/ENDPOINTS.md", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs: write docs/ENDPOINTS.md:", err)
		os.Exit(1)
	}
}
