// Command gendocs regenerates docs/ENDPOINTS.md from internal/endpoints.yaml,
// the single source of truth for endpoint coverage. CI runs this and fails
// the build if the working tree then shows a diff, so docs/ENDPOINTS.md
// can never drift from what's actually implemented.
//
// Run: go run ./internal/gendocs
package main

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

type endpoint struct {
	Method      string `yaml:"method"`
	AccountMode string `yaml:"account_mode"`
	Domain      string `yaml:"domain"`
	HTTPMethod  string `yaml:"http_method"`
	Path        string `yaml:"path"`
	Access      string `yaml:"access"`
	Permission  string `yaml:"permission"`
	Status      string `yaml:"status"`
	Test        string `yaml:"test"`
	DocURL      string `yaml:"doc_url"`
}

type abandoned struct {
	Method string `yaml:"method"`
	Reason string `yaml:"reason"`
	DocURL string `yaml:"doc_url"`
}

type manifest struct {
	Endpoints []endpoint  `yaml:"endpoints"`
	Abandoned []abandoned `yaml:"abandoned"`
}

func main() {
	raw, err := os.ReadFile("internal/endpoints.yaml")
	if err != nil {
		fmt.Fprintln(os.Stderr, "gendocs: read internal/endpoints.yaml:", err)
		os.Exit(1)
	}

	var m manifest
	if err := yaml.Unmarshal(raw, &m); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs: parse internal/endpoints.yaml:", err)
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("# Endpoint Coverage Map\n\n")
	b.WriteString("Generated from [internal/endpoints.yaml](../internal/endpoints.yaml) by `go run ./internal/gendocs` — do not edit this file by hand, edit the manifest and regenerate.\n\n")
	b.WriteString("| Method | Account Mode | Domain | HTTP | Path | Access | Permission | Status | Test | Docs |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|---|---|\n")
	for _, e := range m.Endpoints {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | `%s` | %s | %s | %s | %s | [Link](%s) |\n",
			e.Method, e.AccountMode, e.Domain, e.HTTPMethod, e.Path, e.Access, e.Permission, e.Status, e.Test, e.DocURL)
	}

	b.WriteString("\n## Not Supported / Abandoned\n\n")
	if len(m.Abandoned) == 0 {
		b.WriteString("None tracked yet. See KuCoin's [abandoned-endpoints introduction](https://www.kucoin.com/docs-new/abandoned-endpoints/introduction) for the platform-wide list.\n")
	} else {
		b.WriteString("| Method | Reason | Docs |\n|---|---|---|\n")
		for _, a := range m.Abandoned {
			fmt.Fprintf(&b, "| `%s` | %s | [Link](%s) |\n", a.Method, a.Reason, a.DocURL)
		}
	}

	b.WriteString("\n## Everything else (not yet implemented)\n\n")
	b.WriteString("Covered so far: the complete current UTA REST v2 market-data group; retained UTA REST v1 market/account/orders/positions/leverage compatibility services; Classic Spot market data and high-frequency/stop/OCO/DCP orders; Classic Futures seed orders/positions; Classic Margin market/orders/debit; and generic reconnecting Classic/UTA WebSocket clients. UTA v2 WebSocket private channels use post-welcome signed authentication and ticker has a typed stream. Not yet implemented: most UTA REST v2 account, funding, transfer, withdrawal, sub-account and trading endpoints; most typed WebSocket payloads and WebSocket order entry; the broader Classic account/funding, Futures and Margin Credit surfaces; and specialty domains (Earn, VIP Lending, Convert, Broker, Affiliate and Copy Trading). See [docs/API_COVERAGE.md](API_COVERAGE.md) and the root [README.md](../README.md#status) for the evidence-backed scope.\n")

	if err := os.WriteFile("docs/ENDPOINTS.md", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs: write docs/ENDPOINTS.md:", err)
		os.Exit(1)
	}
}
