package orders

import (
	"context"
	"errors"
	"net/http"
	"strconv"

	"github.com/tigusigalpa/kucoin-go/transport"
)

// ErrMutuallyExclusiveSize is returned locally (no network call) when
// more than one of Size/Qty/ValueQty is set on a PlaceOrderRequest.
var ErrMutuallyExclusiveSize = errors.New("kucoin: set at most one of Size, Qty, or ValueQty")

// ErrLimitOrderRequiresPrice is returned locally (no network call) when a
// non-market, non-close order has no price set.
var ErrLimitOrderRequiresPrice = errors.New("kucoin: a limit order requires Price")

// Client provides a seed set of KuCoin Classic Futures' private
// order-management endpoints. Every method requires credentials with the
// Futures (write) or General (read) permission; calls return
// transport.ErrCredentialsRequired locally (no network call) if none are
// configured.
type Client struct {
	executor *transport.Executor
}

// NewClient wires an orders.Client to the shared Classic Futures
// Executor. Not normally called directly; use kucoin.NewClient.
func NewClient(executor *transport.Executor) *Client {
	return &Client{executor: executor}
}

func validatePlaceOrder(req PlaceOrderRequest) error {
	set := 0
	if req.Size != 0 {
		set++
	}
	if req.Qty != "" {
		set++
	}
	if req.ValueQty != "" {
		set++
	}
	if set > 1 {
		return ErrMutuallyExclusiveSize
	}
	if !req.CloseOrder && (req.Type == "" || req.Type == "limit") && req.Price == "" {
		return ErrLimitOrderRequiresPrice
	}
	return nil
}

// PlaceOrder submits a new Classic Futures order. req.ClientOid is sent
// as-is (never generated by this SDK) and is required by KuCoin.
//
// Docs: https://www.kucoin.com/docs-new/rest/futures-trading/orders/add-order
func (c *Client) PlaceOrder(ctx context.Context, req PlaceOrderRequest) (*OrderRef, error) {
	if err := validatePlaceOrder(req); err != nil {
		return nil, err
	}
	var result OrderRef
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/v1/orders", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PlaceOrderTest validates a Classic Futures order (signature/params only
// — it never reaches the matching engine and cannot be queried
// afterward). Same parameters as PlaceOrder.
//
// Docs: https://www.kucoin.com/docs-new/rest/futures-trading/orders/add-order-test
func (c *Client) PlaceOrderTest(ctx context.Context, req PlaceOrderRequest) (*OrderRef, error) {
	if err := validatePlaceOrder(req); err != nil {
		return nil, err
	}
	var result OrderRef
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/v1/orders/test", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrderByID looks up a single order (including stop orders) by its
// KuCoin-assigned ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/futures-trading/orders/get-order-by-orderld
func (c *Client) GetOrderByID(ctx context.Context, orderID string) (*Order, error) {
	var result Order
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/orders/"+orderID, nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrderListOptions are the optional filters for GetOrderList. "done"
// orders are limited to a 7-day startAt/endAt range; "active" orders have
// no time-range limit.
type GetOrderListOptions struct {
	Status      string // active, done (default done)
	Symbol      string
	Side        string // buy, sell
	Type        string // limit, market, limit_stop, market_stop, oco_limit, oco_stop
	StartAt     int64  // Unix milliseconds
	EndAt       int64  // Unix milliseconds
	CurrentPage int
	PageSize    int // default 50, max 1000
}

// GetOrderList lists orders, paginated by page number (not cursor).
//
// Docs: https://www.kucoin.com/docs-new/rest/futures-trading/orders/get-order-list
func (c *Client) GetOrderList(ctx context.Context, opts GetOrderListOptions) (*OrderListPage, error) {
	query := map[string]string{}
	if opts.Status != "" {
		query["status"] = opts.Status
	}
	if opts.Symbol != "" {
		query["symbol"] = opts.Symbol
	}
	if opts.Side != "" {
		query["side"] = opts.Side
	}
	if opts.Type != "" {
		query["type"] = opts.Type
	}
	if opts.StartAt != 0 {
		query["startAt"] = strconv.FormatInt(opts.StartAt, 10)
	}
	if opts.EndAt != 0 {
		query["endAt"] = strconv.FormatInt(opts.EndAt, 10)
	}
	if opts.CurrentPage > 0 {
		query["currentPage"] = strconv.Itoa(opts.CurrentPage)
	}
	if opts.PageSize > 0 {
		query["pageSize"] = strconv.Itoa(opts.PageSize)
	}
	var result OrderListPage
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/orders", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
