package orders

import (
	"context"
	"errors"
	"net/http"
	"strconv"

	"github.com/tigusigalpa/kucoin-go/transport"
)

// ErrOrderIDOrClientOidRequired is returned locally (no network call) when
// neither OrderID nor ClientOid is set on a cancel request.
var ErrOrderIDOrClientOidRequired = errors.New("kucoin: either OrderID or ClientOid is required")

// ErrTooManyBatchCancelItems is returned locally (no network call) when a
// batch cancel request exceeds KuCoin's documented limit of 20 items.
var ErrTooManyBatchCancelItems = errors.New("kucoin: batch cancel accepts at most 20 items")

// Client provides KuCoin UTA's private order-management endpoints. Every
// method requires credentials; calls return transport.ErrCredentialsRequired
// locally (no network call) if none are configured.
type Client struct {
	executor *transport.Executor
}

// NewClient wires an orders.Client to the shared UTA Executor. Not
// normally called directly; use kucoin.NewClient.
func NewClient(executor *transport.Executor) *Client {
	return &Client{executor: executor}
}

// PlaceOrder submits a new UTA order. See PlaceOrderRequest for field
// semantics; req.ClientOid is sent as-is (never generated by this SDK).
//
// Docs: https://www.kucoin.com/docs-new/rest/ua/place-order
func (c *Client) PlaceOrder(ctx context.Context, req PlaceOrderRequest) (*OrderRef, error) {
	var result OrderRef
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/ua/v1/unified/order/place", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelOrder cancels a single order. req must set OrderID and/or
// ClientOid; if neither is set, ErrOrderIDOrClientOidRequired is returned
// locally with no network call.
//
// Docs: https://www.kucoin.com/docs-new/rest/ua/cancel-order
func (c *Client) CancelOrder(ctx context.Context, req CancelOrderRequest) (*CancelOrderResult, error) {
	if req.OrderID == "" && req.ClientOid == "" {
		return nil, ErrOrderIDOrClientOidRequired
	}
	var result CancelOrderResult
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/ua/v1/unified/order/cancel", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BatchCancelOrderByID cancels up to 20 specific orders in one call. Each
// item must set OrderID and/or ClientOid, and the list must not exceed 20
// entries; violations return an error locally with no network call.
//
// Docs: https://www.kucoin.com/docs-new/rest/ua/batch-cancel-order-by-id
func (c *Client) BatchCancelOrderByID(ctx context.Context, req BatchCancelByIDRequest) (*BatchCancelResult, error) {
	if len(req.CancelOrderList) > 20 {
		return nil, ErrTooManyBatchCancelItems
	}
	for _, item := range req.CancelOrderList {
		if item.OrderID == "" && item.ClientOid == "" {
			return nil, ErrOrderIDOrClientOidRequired
		}
	}
	var result BatchCancelResult
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/ua/v1/unified/order/cancel-batch", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BatchCancelOrderBySymbol cancels every order matching a symbol (up to
// 100 orders). UTA mode only supports SPOT/FUTURES; Spot Cross/Isolated
// Margin is not supported by this endpoint.
//
// Docs: https://www.kucoin.com/docs-new/rest/ua/batch-cancel-order-by-symbol
func (c *Client) BatchCancelOrderBySymbol(ctx context.Context, req BatchCancelBySymbolRequest) (*BatchCancelResult, error) {
	var result BatchCancelResult
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/ua/v1/unified/order/cancel-all", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrderDetails looks up a single order by OrderID or ClientOid (at
// least one is required; OrderID takes priority if both are set).
//
// Docs: https://www.kucoin.com/docs-new/rest/ua/get-order-details
func (c *Client) GetOrderDetails(ctx context.Context, tradeType, symbol, orderID, clientOid string) (*Order, error) {
	if orderID == "" && clientOid == "" {
		return nil, ErrOrderIDOrClientOidRequired
	}
	query := map[string]string{"tradeType": tradeType, "symbol": symbol}
	if orderID != "" {
		query["orderId"] = orderID
	}
	if clientOid != "" {
		query["clientOid"] = clientOid
	}
	var result Order
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/ua/v1/unified/order/detail", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOpenOrderListOptions are the optional filters for GetOpenOrderList.
type GetOpenOrderListOptions struct {
	Symbol      string
	OrderFilter string // NORMAL (default), ADVANCED
	PageNumber  int
	PageSize    int
}

// GetOpenOrderList lists currently unfilled/partially-filled orders,
// sorted by order time descending.
//
// Docs: https://www.kucoin.com/docs-new/rest/ua/get-open-order-list
func (c *Client) GetOpenOrderList(ctx context.Context, tradeType string, opts GetOpenOrderListOptions) (*OpenOrderList, error) {
	query := map[string]string{"tradeType": tradeType}
	if opts.Symbol != "" {
		query["symbol"] = opts.Symbol
	}
	if opts.OrderFilter != "" {
		query["orderFilter"] = opts.OrderFilter
	}
	if opts.PageNumber > 0 {
		query["pageNumber"] = strconv.Itoa(opts.PageNumber)
	}
	if opts.PageSize > 0 {
		query["pageSize"] = strconv.Itoa(opts.PageSize)
	}
	var result OpenOrderList
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/ua/v1/unified/order/open-list", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrderHistoryOptions are the optional filters for GetOrderHistory.
// StartAt/EndAt default to the last 7 days when zero.
type GetOrderHistoryOptions struct {
	Symbol      string
	Side        string // BUY, SELL
	OrderFilter string // NORMAL (default), ADVANCED
	StartAt     int64  // Unix milliseconds
	EndAt       int64  // Unix milliseconds
	LastID      int64
	PageSize    int
}

// GetOrderHistory lists historical (filled/cancelled) orders.
//
// Docs: https://www.kucoin.com/docs-new/rest/ua/get-order-history
func (c *Client) GetOrderHistory(ctx context.Context, tradeType string, opts GetOrderHistoryOptions) (*OrderHistoryPage, error) {
	query := map[string]string{"tradeType": tradeType}
	if opts.Symbol != "" {
		query["symbol"] = opts.Symbol
	}
	if opts.Side != "" {
		query["side"] = opts.Side
	}
	if opts.OrderFilter != "" {
		query["orderFilter"] = opts.OrderFilter
	}
	if opts.StartAt != 0 {
		query["startAt"] = strconv.FormatInt(opts.StartAt, 10)
	}
	if opts.EndAt != 0 {
		query["endAt"] = strconv.FormatInt(opts.EndAt, 10)
	}
	if opts.LastID != 0 {
		query["lastId"] = strconv.FormatInt(opts.LastID, 10)
	}
	if opts.PageSize > 0 {
		query["pageSize"] = strconv.Itoa(opts.PageSize)
	}
	var result OrderHistoryPage
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/ua/v1/unified/order/history", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetTradeHistoryOptions are the optional filters for GetTradeHistory.
// StartAt/EndAt default to the last 7 days when zero.
type GetTradeHistoryOptions struct {
	Symbol   string
	OrderID  string
	Side     string // BUY, SELL
	StartAt  int64  // Unix milliseconds
	EndAt    int64  // Unix milliseconds
	LastID   string // opaque cursor
	PageSize int
}

// GetTradeHistory lists fill/execution records.
//
// Docs: https://www.kucoin.com/docs-new/rest/ua/get-trade-history
func (c *Client) GetTradeHistory(ctx context.Context, tradeType string, opts GetTradeHistoryOptions) (*TradeHistoryPage, error) {
	query := map[string]string{"tradeType": tradeType}
	if opts.Symbol != "" {
		query["symbol"] = opts.Symbol
	}
	if opts.OrderID != "" {
		query["orderId"] = opts.OrderID
	}
	if opts.Side != "" {
		query["side"] = opts.Side
	}
	if opts.StartAt != 0 {
		query["startAt"] = strconv.FormatInt(opts.StartAt, 10)
	}
	if opts.EndAt != 0 {
		query["endAt"] = strconv.FormatInt(opts.EndAt, 10)
	}
	if opts.LastID != "" {
		query["lastId"] = opts.LastID
	}
	if opts.PageSize > 0 {
		query["pageSize"] = strconv.Itoa(opts.PageSize)
	}
	var result TradeHistoryPage
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/ua/v1/unified/order/execution", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
