package orders

import (
	"context"
	"errors"
	"net/http"
	"strconv"

	"github.com/tigusigalpa/kucoin-go/transport"
)

// ErrLimitOrderRequiresPrice is returned locally (no network call) when a
// "limit" order request has no price set.
var ErrLimitOrderRequiresPrice = errors.New("kucoin: a limit order requires Price")

// Client provides KuCoin Classic Margin's private order-management
// endpoints. Every method requires credentials; calls return
// transport.ErrCredentialsRequired locally (no network call) if none are
// configured.
type Client struct {
	executor *transport.Executor
}

// NewClient wires an orders.Client to the shared Classic Executor. Not
// normally called directly; use kucoin.NewClient.
func NewClient(executor *transport.Executor) *Client {
	return &Client{executor: executor}
}

func validatePlaceOrder(req PlaceOrderRequest) error {
	if (req.Type == "" || req.Type == "limit") && req.Price == "" {
		return ErrLimitOrderRequiresPrice
	}
	return nil
}

// PlaceOrder submits a new Classic Margin order. req.ClientOid is sent
// as-is (never generated by this SDK) and is required by KuCoin.
//
// Docs: https://www.kucoin.com/docs-new/rest/margin-trading/orders/add-order
func (c *Client) PlaceOrder(ctx context.Context, req PlaceOrderRequest) (*OrderRef, error) {
	if err := validatePlaceOrder(req); err != nil {
		return nil, err
	}
	var result OrderRef
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/v3/hf/margin/order", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelOrderByID cancels a single order by its KuCoin-assigned ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/margin-trading/orders/cancel-order-by-orderid
func (c *Client) CancelOrderByID(ctx context.Context, orderID, symbol string) (*CancelByOrderIDResult, error) {
	var result CancelByOrderIDResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v3/hf/margin/orders/"+orderID, map[string]string{"symbol": symbol}, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelOrderByClientOid cancels a single order by its caller-assigned
// client order ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/margin-trading/orders/cancel-order-by-clientoid
func (c *Client) CancelOrderByClientOid(ctx context.Context, clientOid, symbol string) (*CancelByClientOidResult, error) {
	var result CancelByClientOidResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v3/hf/margin/orders/client-order/"+clientOid, map[string]string{"symbol": symbol}, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelAllOrders cancels every open order for a symbol within one trade
// type (cross or isolated). Unlike Classic Spot's account-wide cancel,
// this is scoped to a single symbol/tradeType pair.
//
// Docs: https://www.kucoin.com/docs-new/rest/margin-trading/orders/cancel-all-orders-by-symbol
func (c *Client) CancelAllOrders(ctx context.Context, symbol, tradeType string) (string, error) {
	var result string
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v3/hf/margin/orders", map[string]string{"symbol": symbol, "tradeType": tradeType}, nil, &result); err != nil {
		return "", err
	}
	return result, nil
}

// GetOrderByID looks up a single order by its KuCoin-assigned ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/margin-trading/orders/get-order-by-orderid
func (c *Client) GetOrderByID(ctx context.Context, orderID, symbol string) (*Order, error) {
	var result Order
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v3/hf/margin/orders/"+orderID, map[string]string{"symbol": symbol}, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrderByClientOid looks up a single order by its caller-assigned
// client order ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/margin-trading/orders/get-order-by-clientoid
func (c *Client) GetOrderByClientOid(ctx context.Context, clientOid, symbol string) (*Order, error) {
	var result Order
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v3/hf/margin/orders/client-order/"+clientOid, map[string]string{"symbol": symbol}, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOpenOrders lists every unfilled/partially-filled order for a symbol
// within one trade type (cross or isolated). Unbounded — no pagination
// parameters exist for this endpoint.
//
// Docs: https://www.kucoin.com/docs-new/rest/margin-trading/orders/get-open-orders
func (c *Client) GetOpenOrders(ctx context.Context, symbol, tradeType string) ([]Order, error) {
	var result []Order
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v3/hf/margin/orders/active", map[string]string{"symbol": symbol, "tradeType": tradeType}, nil, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// GetClosedOrdersOptions are the optional filters for GetClosedOrders.
type GetClosedOrdersOptions struct {
	Side    string // buy, sell
	Type    string // limit, market
	LastID  int64
	Limit   int   // 1-100, default 20
	StartAt int64 // Unix milliseconds
	EndAt   int64 // Unix milliseconds
}

// GetClosedOrders lists historical (filled/cancelled) orders for a
// symbol within one trade type.
//
// Docs: https://www.kucoin.com/docs-new/rest/margin-trading/orders/get-closed-orders
func (c *Client) GetClosedOrders(ctx context.Context, symbol, tradeType string, opts GetClosedOrdersOptions) (*ClosedOrderPage, error) {
	query := map[string]string{"symbol": symbol, "tradeType": tradeType}
	if opts.Side != "" {
		query["side"] = opts.Side
	}
	if opts.Type != "" {
		query["type"] = opts.Type
	}
	if opts.LastID != 0 {
		query["lastId"] = strconv.FormatInt(opts.LastID, 10)
	}
	if opts.Limit > 0 {
		query["limit"] = strconv.Itoa(opts.Limit)
	}
	if opts.StartAt != 0 {
		query["startAt"] = strconv.FormatInt(opts.StartAt, 10)
	}
	if opts.EndAt != 0 {
		query["endAt"] = strconv.FormatInt(opts.EndAt, 10)
	}
	var result ClosedOrderPage
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v3/hf/margin/orders/done", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetTradeHistoryOptions are the optional filters for GetTradeHistory.
type GetTradeHistoryOptions struct {
	OrderID string
	Side    string
	Type    string
	LastID  int64
	Limit   int   // default 20, max 100
	StartAt int64 // Unix milliseconds
	EndAt   int64 // Unix milliseconds
}

// GetTradeHistory lists fill/execution records for a symbol within one
// trade type.
//
// Docs: https://www.kucoin.com/docs-new/rest/margin-trading/orders/get-trade-history
func (c *Client) GetTradeHistory(ctx context.Context, symbol, tradeType string, opts GetTradeHistoryOptions) (*FillPage, error) {
	query := map[string]string{"symbol": symbol, "tradeType": tradeType}
	if opts.OrderID != "" {
		query["orderId"] = opts.OrderID
	}
	if opts.Side != "" {
		query["side"] = opts.Side
	}
	if opts.Type != "" {
		query["type"] = opts.Type
	}
	if opts.LastID != 0 {
		query["lastId"] = strconv.FormatInt(opts.LastID, 10)
	}
	if opts.Limit > 0 {
		query["limit"] = strconv.Itoa(opts.Limit)
	}
	if opts.StartAt != 0 {
		query["startAt"] = strconv.FormatInt(opts.StartAt, 10)
	}
	if opts.EndAt != 0 {
		query["endAt"] = strconv.FormatInt(opts.EndAt, 10)
	}
	var result FillPage
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v3/hf/margin/fills", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
