package orders

import (
	"context"
	"errors"
	"net/http"
	"strconv"

	"github.com/tigusigalpa/kucoin-go/transport"
)

// ErrTooManyBatchOrders is returned locally (no network call) when a
// batch order request exceeds KuCoin's documented limit of 20 items.
var ErrTooManyBatchOrders = errors.New("kucoin: batch add accepts at most 20 orders")

// ErrLimitOrderRequiresPrice is returned locally (no network call) when a
// "limit" order request has no price set.
var ErrLimitOrderRequiresPrice = errors.New("kucoin: a limit order requires Price")

// Client provides KuCoin Classic Spot's private order-management
// endpoints. Every method requires credentials; calls return
// transport.ErrCredentialsRequired locally (no network call) if none are
// configured.
type Client struct {
	executor *transport.Executor
}

// NewClient wires an orders.Client to the shared Classic Executor. Not
// normally called directly; use kucoin.NewClient.
func NewClient(executor *transport.Executor) *Client {
	return &Client{executor: executor}
}

func validatePlaceOrder(req PlaceOrderRequest) error {
	if req.Type == "limit" && req.Price == "" {
		return ErrLimitOrderRequiresPrice
	}
	return nil
}

// PlaceOrder submits a new Classic Spot order. req.ClientOid is sent
// as-is (never generated by this SDK).
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/add-order
func (c *Client) PlaceOrder(ctx context.Context, req PlaceOrderRequest) (*OrderRef, error) {
	if err := validatePlaceOrder(req); err != nil {
		return nil, err
	}
	var result OrderRef
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/v1/hf/orders", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PlaceOrderTest validates a Classic Spot order (signature/params only —
// it never reaches the matching engine and cannot be queried afterward).
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/add-order-test
func (c *Client) PlaceOrderTest(ctx context.Context, req PlaceOrderRequest) (*OrderRef, error) {
	if err := validatePlaceOrder(req); err != nil {
		return nil, err
	}
	var result OrderRef
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/v1/hf/orders/test", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BatchAddOrders submits up to 20 orders in one call, placed sequentially
// by KuCoin. Results (including fills) must be polled or subscribed to —
// this call only confirms placement, not execution.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/batch-add-orders
func (c *Client) BatchAddOrders(ctx context.Context, orderList []PlaceOrderRequest) ([]BatchOrderResult, error) {
	if len(orderList) > 20 {
		return nil, ErrTooManyBatchOrders
	}
	for _, item := range orderList {
		if err := validatePlaceOrder(item); err != nil {
			return nil, err
		}
	}
	body := struct {
		OrderList []PlaceOrderRequest `json:"orderList"`
	}{OrderList: orderList}
	var result []BatchOrderResult
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/v1/hf/orders/multi", nil, body, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// CancelOrderByID cancels a single order by its KuCoin-assigned ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-order-by-orderld
func (c *Client) CancelOrderByID(ctx context.Context, orderID, symbol string) (*CancelByOrderIDResult, error) {
	var result CancelByOrderIDResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v1/hf/orders/"+orderID, map[string]string{"symbol": symbol}, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelOrderByClientOid cancels a single order by its caller-assigned
// client order ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-order-by-clientoid
func (c *Client) CancelOrderByClientOid(ctx context.Context, clientOid, symbol string) (*CancelByClientOidResult, error) {
	var result CancelByClientOidResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v1/hf/orders/client-order/"+clientOid, map[string]string{"symbol": symbol}, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelAllOrders cancels every Classic Spot HF order across all symbols
// for the account. There is no symbol/category filter — this is an
// account-wide operation.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-all-orders
func (c *Client) CancelAllOrders(ctx context.Context) (*CancelAllResult, error) {
	var result CancelAllResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v1/hf/orders/cancelAll", nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOrderByID looks up a single order. Canceled orders are queryable up
// to 2 days back, filled orders up to 7 days back; older requests are
// silently clamped to that window by KuCoin.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-order-by-orderld
func (c *Client) GetOrderByID(ctx context.Context, orderID, symbol string) (*Order, error) {
	var result Order
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/hf/orders/"+orderID, map[string]string{"symbol": symbol}, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOpenOrders lists every unfilled/partially-filled order for a symbol.
// Unbounded — no pagination parameters exist for this endpoint.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-open-orders
func (c *Client) GetOpenOrders(ctx context.Context, symbol string) ([]Order, error) {
	var result []Order
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/hf/orders/active", map[string]string{"symbol": symbol}, nil, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// GetClosedOrdersOptions are the optional filters for GetClosedOrders.
type GetClosedOrdersOptions struct {
	Side    string // buy, sell
	Type    string // limit, market
	LastID  int64
	Limit   int   // 1-100, default 20
	StartAt int64 // Unix milliseconds
	EndAt   int64 // Unix milliseconds
}

// GetClosedOrders lists historical (filled/cancelled) orders for a
// symbol. Same 2-day/7-day historical window as GetOrderByID.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-closed-orders
func (c *Client) GetClosedOrders(ctx context.Context, symbol string, opts GetClosedOrdersOptions) (*ClosedOrderPage, error) {
	query := map[string]string{"symbol": symbol}
	if opts.Side != "" {
		query["side"] = opts.Side
	}
	if opts.Type != "" {
		query["type"] = opts.Type
	}
	if opts.LastID != 0 {
		query["lastId"] = strconv.FormatInt(opts.LastID, 10)
	}
	if opts.Limit > 0 {
		query["limit"] = strconv.Itoa(opts.Limit)
	}
	if opts.StartAt != 0 {
		query["startAt"] = strconv.FormatInt(opts.StartAt, 10)
	}
	if opts.EndAt != 0 {
		query["endAt"] = strconv.FormatInt(opts.EndAt, 10)
	}
	var result ClosedOrderPage
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/hf/orders/done", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetTradeHistoryOptions are the optional filters for GetTradeHistory. If
// OrderID is set, every other filter is ignored by KuCoin.
type GetTradeHistoryOptions struct {
	OrderID string
	Side    string
	Type    string
	LastID  int64
	Limit   int   // 1-100, default 20
	StartAt int64 // Unix milliseconds
	EndAt   int64 // Unix milliseconds
}

// GetTradeHistory lists fill/execution records for a symbol
// ("hf/fills" on the wire — distinct from the public recent-trades
// market-data endpoint of a similar name). Lookback is capped at 7 days
// for orders that are no longer active.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-trade-history
func (c *Client) GetTradeHistory(ctx context.Context, symbol string, opts GetTradeHistoryOptions) (*FillPage, error) {
	query := map[string]string{"symbol": symbol}
	if opts.OrderID != "" {
		query["orderId"] = opts.OrderID
	}
	if opts.Side != "" {
		query["side"] = opts.Side
	}
	if opts.Type != "" {
		query["type"] = opts.Type
	}
	if opts.LastID != 0 {
		query["lastId"] = strconv.FormatInt(opts.LastID, 10)
	}
	if opts.Limit > 0 {
		query["limit"] = strconv.Itoa(opts.Limit)
	}
	if opts.StartAt != 0 {
		query["startAt"] = strconv.FormatInt(opts.StartAt, 10)
	}
	if opts.EndAt != 0 {
		query["endAt"] = strconv.FormatInt(opts.EndAt, 10)
	}
	var result FillPage
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/hf/fills", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func validateStopOrder(req StopOrderRequest) error {
	if (req.Type == "" || req.Type == "limit") && req.Price == "" {
		return ErrLimitOrderRequiresPrice
	}
	return nil
}

// AddStopOrder submits a new Classic Spot stop order — a distinct,
// older order family from PlaceOrder's HF orders. Unlike PlaceOrder,
// req.ClientOid is optional (KuCoin does not require it here).
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/add-stop-order
func (c *Client) AddStopOrder(ctx context.Context, req StopOrderRequest) (*StopOrderRef, error) {
	if err := validateStopOrder(req); err != nil {
		return nil, err
	}
	var result StopOrderRef
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/v1/stop-order", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelStopOrderByID cancels a single stop order by its KuCoin-assigned
// ID. KuCoin returns cancelledOrderIds as an array even for this
// single-order call.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-stop-order-by-orderid
func (c *Client) CancelStopOrderByID(ctx context.Context, orderID string) (*CancelStopOrderResult, error) {
	var result CancelStopOrderResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v1/stop-order/"+orderID, nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelStopOrderByClientOid cancels a single stop order by its
// caller-assigned client order ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-stop-order-by-clientoid
func (c *Client) CancelStopOrderByClientOid(ctx context.Context, clientOid, symbol string) (*CancelStopOrderByClientOidResult, error) {
	query := map[string]string{"clientOid": clientOid}
	if symbol != "" {
		query["symbol"] = symbol
	}
	var result CancelStopOrderByClientOidResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v1/stop-order/cancelOrderByClientOid", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelStopOrders cancels every stop order matching the given filters
// (all optional — an empty call cancels every stop order on the
// account). orderIDs is a comma-separated list of KuCoin order IDs.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-stop-orders
func (c *Client) CancelStopOrders(ctx context.Context, symbol, tradeType, orderIDs string) (*CancelStopOrderResult, error) {
	query := map[string]string{}
	if symbol != "" {
		query["symbol"] = symbol
	}
	if tradeType != "" {
		query["tradeType"] = tradeType
	}
	if orderIDs != "" {
		query["orderIds"] = orderIDs
	}
	var result CancelStopOrderResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v1/stop-order/cancel", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetStopOrderByID looks up a single stop order by its KuCoin-assigned
// ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-stop-order-details-by-orderid
func (c *Client) GetStopOrderByID(ctx context.Context, orderID string) (*StopOrder, error) {
	var result StopOrder
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/stop-order/"+orderID, nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetStopOrderByClientOid looks up stop orders by their caller-assigned
// client order ID. Unlike GetStopOrderByID, KuCoin returns an array here
// (a clientOid is not guaranteed unique across a stop order's full
// lifecycle the way an orderId is).
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-stop-order-details-by-clientoid
func (c *Client) GetStopOrderByClientOid(ctx context.Context, clientOid, symbol string) ([]StopOrder, error) {
	query := map[string]string{"clientOid": clientOid}
	if symbol != "" {
		query["symbol"] = symbol
	}
	var result []StopOrder
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/stop-order/queryOrderByClientOid", query, nil, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// GetStopOrderListOptions are the optional filters for GetStopOrderList.
type GetStopOrderListOptions struct {
	Symbol      string
	Side        string
	Type        string
	TradeType   string
	OrderIDs    string // comma-separated
	Stop        string // stop (loss/entry orders), oco
	StartAt     int64  // Unix milliseconds
	EndAt       int64  // Unix milliseconds
	CurrentPage int
	PageSize    int // default 50, range 10-500
}

// GetStopOrderList lists stop orders, paginated by page number (not
// cursor) — unlike GetClosedOrders/GetTradeHistory's cursor pagination.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-stop-order-list
func (c *Client) GetStopOrderList(ctx context.Context, opts GetStopOrderListOptions) (*StopOrderPage, error) {
	query := map[string]string{}
	if opts.Symbol != "" {
		query["symbol"] = opts.Symbol
	}
	if opts.Side != "" {
		query["side"] = opts.Side
	}
	if opts.Type != "" {
		query["type"] = opts.Type
	}
	if opts.TradeType != "" {
		query["tradeType"] = opts.TradeType
	}
	if opts.OrderIDs != "" {
		query["orderIds"] = opts.OrderIDs
	}
	if opts.Stop != "" {
		query["stop"] = opts.Stop
	}
	if opts.StartAt != 0 {
		query["startAt"] = strconv.FormatInt(opts.StartAt, 10)
	}
	if opts.EndAt != 0 {
		query["endAt"] = strconv.FormatInt(opts.EndAt, 10)
	}
	if opts.CurrentPage > 0 {
		query["currentPage"] = strconv.Itoa(opts.CurrentPage)
	}
	if opts.PageSize > 0 {
		query["pageSize"] = strconv.Itoa(opts.PageSize)
	}
	var result StopOrderPage
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/stop-order", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AddOCOOrder submits a new Classic Spot OCO (One-Cancels-the-Other)
// order — a limit-order leg paired with a stop-limit leg. Unlike
// AddStopOrder, req.ClientOid is required by KuCoin.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/add-oco-order
func (c *Client) AddOCOOrder(ctx context.Context, req OCOOrderRequest) (*OCOOrderRef, error) {
	var result OCOOrderRef
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/v3/oco/order", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelOCOOrderByID cancels an OCO pair by its KuCoin-assigned order
// ID. CancelledOrderIDs holds both leg IDs of the cancelled pair.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-oco-order-by-orderid
func (c *Client) CancelOCOOrderByID(ctx context.Context, orderID string) (*CancelOCOOrderResult, error) {
	var result CancelOCOOrderResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v3/oco/order/"+orderID, nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelOCOOrderByClientOid cancels an OCO pair by its caller-assigned
// client order ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-oco-order-by-clientoid
func (c *Client) CancelOCOOrderByClientOid(ctx context.Context, clientOid string) (*CancelOCOOrderResult, error) {
	var result CancelOCOOrderResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v3/oco/client-order/"+clientOid, nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelOCOOrders cancels every OCO pair matching the given filters
// (all optional — an empty call cancels every OCO order on the
// account). orderIDs is a comma-separated list of KuCoin order IDs.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-multiple-oco-orders
func (c *Client) CancelOCOOrders(ctx context.Context, symbol, orderIDs string) (*CancelOCOOrderResult, error) {
	query := map[string]string{}
	if symbol != "" {
		query["symbol"] = symbol
	}
	if orderIDs != "" {
		query["orderIds"] = orderIDs
	}
	var result CancelOCOOrderResult
	if _, err := c.executor.Do(ctx, http.MethodDelete, "/api/v3/oco/orders", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOCOOrderByID looks up an OCO pair's flat summary by its
// KuCoin-assigned order ID. Call GetOCOOrderDetails for leg-level
// detail (price/side/stopPrice per leg).
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-oco-order-info-by-orderid
func (c *Client) GetOCOOrderByID(ctx context.Context, orderID string) (*OCOOrderInfo, error) {
	var result OCOOrderInfo
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v3/oco/order/"+orderID, nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOCOOrderByClientOid looks up an OCO pair's flat summary by its
// caller-assigned client order ID.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-oco-order-info-by-clientoid
func (c *Client) GetOCOOrderByClientOid(ctx context.Context, clientOid string) (*OCOOrderInfo, error) {
	var result OCOOrderInfo
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v3/oco/client-order/"+clientOid, nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOCOOrderDetails looks up an OCO pair's full record, including its
// two constituent leg orders (see OCOOrderLeg) — a separate, more
// detailed endpoint from GetOCOOrderByID's flat summary.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-oco-order-details
func (c *Client) GetOCOOrderDetails(ctx context.Context, orderID string) (*OCOOrderDetails, error) {
	var result OCOOrderDetails
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v3/oco/order/details/"+orderID, nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetOCOOrderListOptions are the optional filters for GetOCOOrderList.
type GetOCOOrderListOptions struct {
	Symbol      string
	OrderIDs    string // comma-separated, up to 500
	StartAt     int64  // Unix milliseconds
	EndAt       int64  // Unix milliseconds
	CurrentPage int
	PageSize    int // default 50, range 10-500
}

// GetOCOOrderList lists OCO pairs (flat summaries — call
// GetOCOOrderDetails per order ID for leg-level detail), paginated by
// page number.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-oco-order-list
func (c *Client) GetOCOOrderList(ctx context.Context, opts GetOCOOrderListOptions) (*OCOOrderPage, error) {
	query := map[string]string{}
	if opts.Symbol != "" {
		query["symbol"] = opts.Symbol
	}
	if opts.OrderIDs != "" {
		query["orderIds"] = opts.OrderIDs
	}
	if opts.StartAt != 0 {
		query["startAt"] = strconv.FormatInt(opts.StartAt, 10)
	}
	if opts.EndAt != 0 {
		query["endAt"] = strconv.FormatInt(opts.EndAt, 10)
	}
	if opts.CurrentPage > 0 {
		query["currentPage"] = strconv.Itoa(opts.CurrentPage)
	}
	if opts.PageSize > 0 {
		query["pageSize"] = strconv.Itoa(opts.PageSize)
	}
	var result OCOOrderPage
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v3/oco/orders", query, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SetDCP configures Disconnect Cancel Protocol (see SetDCPRequest). The
// actual cancel-all fires 0-10s after TriggerTime, only if the account's
// open orders are still cancellable at that time.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/set-dcp
func (c *Client) SetDCP(ctx context.Context, req SetDCPRequest) (*DCPTrigger, error) {
	var result DCPTrigger
	if _, err := c.executor.Do(ctx, http.MethodPost, "/api/v1/hf/orders/dead-cancel-all", nil, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetDCP returns the account's current Disconnect Cancel Protocol
// configuration.
//
// Docs: https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-dcp
func (c *Client) GetDCP(ctx context.Context) (*DCPConfig, error) {
	var result DCPConfig
	if _, err := c.executor.Do(ctx, http.MethodGet, "/api/v1/hf/orders/dead-cancel-all/query", nil, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeactivateDCP disables Disconnect Cancel Protocol. KuCoin has no
// dedicated deactivate endpoint — this is a convenience wrapper around
// SetDCP with Timeout -1.
func (c *Client) DeactivateDCP(ctx context.Context) (*DCPTrigger, error) {
	return c.SetDCP(ctx, SetDCPRequest{Timeout: -1})
}
